---
minimum_pre_commit_version: 1.15.2
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: check-merge-conflict      # Check for files that contain merge conflict strings.
  - id: trailing-whitespace       # Trims trailing whitespace.
    args: [--markdown-linebreak-ext=md]
  - id: mixed-line-ending         # Replaces or checks mixed line ending.
    args: [--fix=lf]
  - id: end-of-file-fixer         # Makes sure files end in a newline and only a newline.
  - id: check-merge-conflict      # Check for files that contain merge conflict strings.
  - id: check-ast                 # Simply check whether files parse as valid python.

- repo: local
  hooks:
  - id: sort-supported-coin-list
    name: Sort Supported Coin List
    entry: .pre-commit-hooks/sort-coins-file.py
    language: python
    files: ^supported_coin_list$

- repo: https://github.com/asottile/pyupgrade
  rev: v2.10.0
  hooks:
  - id: pyupgrade
    name: Rewrite Code to be Py3.6+
    args: [--py36-plus]

- repo: https://github.com/pycqa/isort
  rev: 5.6.3
  hooks:
  - id: isort
    args: [--profile, black, --line-length, '120']

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    args: [-l, '120']

- repo: https://github.com/asottile/blacken-docs
  rev: v1.7.0
  hooks:
  - id: blacken-docs
    args: [--skip-errors]
    files: ^docs/.*\.rst
    additional_dependencies: [black==20.8b1]

- repo: https://github.com/s0undt3ch/pre-commit-populate-pylint-requirements
  rev: aed8c6a
  hooks:
  - id: populate-pylint-requirements
    files: ^(dev-)?requirements\.txt$
    args: [requirements.txt, dev-requirements.txt]

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.4.4
  hooks:
  - id: pylint
    name: PyLint
    args: [--output-format=parseable, --rcfile=.pylintrc]
    additional_dependencies:
    - Flask==1.1.2
    - apprise==0.9.1
    - cachetools==4.2.1
    - eventlet==0.30.2
    - flask-cors==3.0.10
    - flask-socketio==5.0.1
    - gunicorn==20.0.4
    - pylint-sqlalchemy
    - python-binance==0.7.10
    - python-socketio[client]==5.0.4
    - schedule==1.0.0
    - sqlalchemy==1.3.23
    - sqlitedict==1.7.0
